### ISSUE TITLE
Extend support for Estrogen Pathway 

### ISSUE THREAD

**Issue by livtanong** [snpeek/snpeek.github.io#14]
This is based on a discussion with 2d4d_data on reddit (I would guess she is @d6e here, but I can't be sure)

There exists a list of variants and their effects on the ESR1 gene. (See https://www.snpedia.com/index.php/ESR1) Any variant with a magnitude > 0 has some effect on the gene.

There are other genes to scrutinize such as COMT and Aromatase--extend the same pattern to these genes.

To extend support, one needs to update `mps-data.json` with the relevant variants.

- [x] ESR1
- [x] COMT
- [x] Aromatase

**Comment by livtanong** [comment]
For ESR1, these are the variants with a Max Magnitude > 0

1. https://www.snpedia.com/index.php/Rs104893956 (estrogen resistance)
2. https://www.snpedia.com/index.php/Rs9340799 (endometrial cancer and cognitive impairment)
3. https://www.snpedia.com/index.php/Rs121913044 (estrogen resistance)
4. https://www.snpedia.com/index.php/Rs397509428 (estrogen resistance)
5. htps://www.snpedia.com/index.php/Rs2881766 (pregnancy-induced hypertension)
6. https://www.snpedia.com/index.php/Rs2295190 (ovarian cancer risk)

Rs104893956 , Rs121913044, and Rs397509428 all contribute to estrogen resistance, so it's easy to lump them in with the "estrogen deactivation" phenotype, but the others don't quite fit the bill. 

That being said, a lot of the other variants currently listed as "estrogen deactivation" phenotype in `mps-data.json` are seemingly unrelated to estrogen deactivation. Does this mean I should simply add support for all 6 variants?

**Comment by livtanong** [comment]
For COMT, there is only one novel variant:
https://www.snpedia.com/index.php/Rs165631 (Breast cancer protection)

The others in this list (https://www.snpedia.com/index.php/COMT) are already present.

I'm not sure what phenotype to add to this, however. Any advice?

**Comment by d6e** [comment]
> This is based on a discussion with 2d4d_data on reddit (I would guess she is @d6e here, but I can't be sure)
> 
> There exists a list of variants and their effects on the ESR1 gene. (See https://www.snpedia.com/index.php/ESR1) Any variant with a magnitude > 0 has some effect on the gene.
> 
> There are other genes to scrutinize such as COMT and Aromatase--extend the same pattern to these genes.
> 
> To extend support, one needs to update `mps-data.json` with the relevant variants.
> 
>     * [ ]  ESR1
> 
>     * [ ]  COMT
> 
>     * [ ]  Aromatase

I'm actually not 2d4d. I'm a different person with a mixed alphanumeric name 🤣 

> For COMT, there is only one novel variant: https://www.snpedia.com/index.php/Rs165631 (Breast cancer protection)
> 
> The others in this list (https://www.snpedia.com/index.php/COMT) are already present.
> 
> I'm not sure what phenotype to add to this, however. Any advice?

I would just lump it under Estrogen Deactivation, it's not perfectly descriptive, I'm open to alternative suggestions 😄 

Thank you for your contribution!

**Comment by livtanong** [comment]
> I'm actually not 2d4d. I'm a different person with a mixed alphanumeric name 🤣

Oops! Sorry for conflating you 😅 

> I would just lump it under Estrogen Deactivation, it's not perfectly descriptive, I'm open to alternative suggestions 😄

I think for now Estrogen Deactivation will be fine. Perhaps I'll have a better idea once I understand all this better.

I have a follow-up question. https://www.snpedia.com/index.php/Rs165631 None of the genotypes are pathogenic based on my understanding, so in this case, the "pathogenic" field should be an empty array, yes?

**Comment by d6e** [comment]
> I have a follow-up question. https://www.snpedia.com/index.php/Rs165631 None of the genotypes are pathogenic based on my understanding, so in this case, the "pathogenic" field should be an empty array, yes?

Huh, that's a good point, I think that one came from 2d4d's original list that she gave me of pathogenic variants. I'm not sure what the reasoning was behind that being included in the list

**Comment by livtanong** [comment]
The latest commit by @r0ze-at-github should address the remaining questions we had.
