### ISSUE TITLE
Unable to analyze AncestryDNA

### ISSUE THREAD

**Issue by MilesBHuff** [snpeek/snpeek.github.io#2]
Any attempts to analyze AncestryDNA are met with "Unable to determine the filetype from the header.".

**Comment by MilesBHuff** [comment]
Looks like the header you're looking for is outdated.  The first line of AncestryDNA exports is now `#AncestryDNA raw data download`.

**Comment by d6e** [comment]
Yeah I think the file I had for it was wrong. Thanks!
