### ISSUE TITLE
Nebula Support

### ISSUE THREAD

**Issue by livtanong** [snpeek/snpeek.github.io#26]
Will need @d6e 's help with a sample file so I can write the parser for this.

**Comment by d6e** [comment]
Nebula? Like https://nebula.org? We already support them with vcf files

**Comment by livtanong** [comment]
Oh sorry, I got confused with the tag. I meant to tag 2d4d, a.k.a. @r0ze-at-github  😅 

I added this task because it's one of the first things that 2d4d asked me to help out with. Since we already have support via VCF, I'll close this comment.
